-- MySQL Script generated by MySQL Workbench
-- Mon May 11 11:55:49 2026
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema steam_db
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema steam_db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `steam_db` DEFAULT CHARACTER SET utf8 ;
USE `steam_db` ;

-- -----------------------------------------------------
-- Table `steam_db`.`game_genre`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `steam_db`.`game_genre` (
  `id_game_genre` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NULL,
  `description` LONGTEXT NULL,
  PRIMARY KEY (`id_game_genre`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `steam_db`.`developer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `steam_db`.`developer` (
  `id_developer` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NULL,
  `description` LONGTEXT NULL,
  PRIMARY KEY (`id_developer`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `steam_db`.`game`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `steam_db`.`game` (
  `id_game` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NULL,
  `developer_id` INT NOT NULL,
  `release_date` DATE NULL,
  `image` VARCHAR(255) NULL,
  `description` LONGTEXT NULL,
  `storage_space` INT NULL,
  `windows_support` TINYINT NULL,
  `mac_support` TINYINT NULL,
  `linux_support` TINYINT NULL,
  PRIMARY KEY (`id_game`),
  INDEX `fk_game_developer1_idx` (`developer_id` ASC) VISIBLE,
  CONSTRAINT `fk_game_developer1`
    FOREIGN KEY (`developer_id`)
    REFERENCES `steam_db`.`developer` (`id_developer`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `steam_db`.`player`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `steam_db`.`player` (
  `id_player` INT NOT NULL AUTO_INCREMENT,
  `nickname` VARCHAR(255) NULL,
  `name` VARCHAR(255) NULL,
  `registration_day` DATE NULL,
  PRIMARY KEY (`id_player`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `steam_db`.`game_player`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `steam_db`.`game_player` (
  `game_id` INT NOT NULL,
  `player_id` INT NOT NULL,
  PRIMARY KEY (`game_id`, `player_id`),
  INDEX `fk_Game_has_Player_Player1_idx` (`player_id` ASC) VISIBLE,
  INDEX `fk_Game_has_Player_Game1_idx` (`game_id` ASC) VISIBLE,
  CONSTRAINT `fk_Game_has_Player_Game1`
    FOREIGN KEY (`game_id`)
    REFERENCES `steam_db`.`game` (`id_game`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Game_has_Player_Player1`
    FOREIGN KEY (`player_id`)
    REFERENCES `steam_db`.`player` (`id_player`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `steam_db`.`operating_system`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `steam_db`.`operating_system` (
  `id_operating_system` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NULL,
  `description` VARCHAR(255) NULL,
  PRIMARY KEY (`id_operating_system`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `steam_db`.`operating_system_game`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `steam_db`.`operating_system_game` (
  `operating_system_id` INT NOT NULL,
  `game_id` INT NOT NULL,
  PRIMARY KEY (`operating_system_id`, `game_id`),
  INDEX `fk_operating_system_has_game_game1_idx` (`game_id` ASC) VISIBLE,
  INDEX `fk_operating_system_has_game_operating_system1_idx` (`operating_system_id` ASC) VISIBLE,
  CONSTRAINT `fk_operating_system_has_game_operating_system1`
    FOREIGN KEY (`operating_system_id`)
    REFERENCES `steam_db`.`operating_system` (`id_operating_system`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_operating_system_has_game_game1`
    FOREIGN KEY (`game_id`)
    REFERENCES `steam_db`.`game` (`id_game`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `steam_db`.`achievement`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `steam_db`.`achievement` (
  `id_achievement` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NULL,
  `game_id` INT NOT NULL,
  `number_of_people` INT NULL,
  `description` MEDIUMTEXT NULL,
  PRIMARY KEY (`id_achievement`),
  INDEX `fk_achievement_game1_idx` (`game_id` ASC) VISIBLE,
  CONSTRAINT `fk_achievement_game1`
    FOREIGN KEY (`game_id`)
    REFERENCES `steam_db`.`game` (`id_game`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `steam_db`.`game_genre_game`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `steam_db`.`game_genre_game` (
  `game_genre_id_game_genre` INT NOT NULL,
  `game_id_game` INT NOT NULL,
  PRIMARY KEY (`game_genre_id_game_genre`, `game_id_game`),
  INDEX `fk_game_genre_has_game_game1_idx` (`game_id_game` ASC) VISIBLE,
  INDEX `fk_game_genre_has_game_game_genre1_idx` (`game_genre_id_game_genre` ASC) VISIBLE,
  CONSTRAINT `fk_game_genre_has_game_game_genre1`
    FOREIGN KEY (`game_genre_id_game_genre`)
    REFERENCES `steam_db`.`game_genre` (`id_game_genre`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_game_genre_has_game_game1`
    FOREIGN KEY (`game_id_game`)
    REFERENCES `steam_db`.`game` (`id_game`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;