-- MySQL Script generated by MySQL Workbench
-- Mon May 11 11:55:49 2026
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema steam_db
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema steam_db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `steam_db` DEFAULT CHARACTER SET utf8 ;
USE `steam_db` ;

-- -----------------------------------------------------
-- Table `steam_db`.`game_genre`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `steam_db`.`game_genre` (
  `id_game_genre` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NULL,
  `description` LONGTEXT NULL,
  PRIMARY KEY (`id_game_genre`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `steam_db`.`developer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `steam_db`.`developer` (
  `id_developer` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NULL,
  `description` LONGTEXT NULL,
  PRIMARY KEY (`id_developer`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `steam_db`.`game`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `steam_db`.`game` (
  `id_game` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NULL,
  `developer_id` INT NOT NULL,
  `release_date` DATE NULL,
  `image` VARCHAR(255) NULL,
  `description` LONGTEXT NULL,
  `storage_space` INT NULL,
  `windows_support` TINYINT NULL,
  `mac_support` TINYINT NULL,
  `linux_support` TINYINT NULL,
  PRIMARY KEY (`id_game`),
  INDEX `fk_game_developer1_idx` (`developer_id` ASC) VISIBLE,
  CONSTRAINT `fk_game_developer1`
    FOREIGN KEY (`developer_id`)
    REFERENCES `steam_db`.`developer` (`id_developer`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `steam_db`.`player`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `steam_db`.`player` (
  `id_player` INT NOT NULL AUTO_INCREMENT,
  `nickname` VARCHAR(255) NULL,
  `name` VARCHAR(255) NULL,
  `registration_day` DATE NULL,
  PRIMARY KEY (`id_player`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `steam_db`.`game_player`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `steam_db`.`game_player` (
  `game_id` INT NOT NULL,
  `player_id` INT NOT NULL,
  PRIMARY KEY (`game_id`, `player_id`),
  INDEX `fk_Game_has_Player_Player1_idx` (`player_id` ASC) VISIBLE,
  INDEX `fk_Game_has_Player_Game1_idx` (`game_id` ASC) VISIBLE,
  CONSTRAINT `fk_Game_has_Player_Game1`
    FOREIGN KEY (`game_id`)
    REFERENCES `steam_db`.`game` (`id_game`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Game_has_Player_Player1`
    FOREIGN KEY (`player_id`)
    REFERENCES `steam_db`.`player` (`id_player`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `steam_db`.`operating_system`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `steam_db`.`operating_system` (
  `id_operating_system` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NULL,
  `description` VARCHAR(255) NULL,
  PRIMARY KEY (`id_operating_system`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `steam_db`.`operating_system_game`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `steam_db`.`operating_system_game` (
  `operating_system_id` INT NOT NULL,
  `game_id` INT NOT NULL,
  PRIMARY KEY (`operating_system_id`, `game_id`),
  INDEX `fk_operating_system_has_game_game1_idx` (`game_id` ASC) VISIBLE,
  INDEX `fk_operating_system_has_game_operating_system1_idx` (`operating_system_id` ASC) VISIBLE,
  CONSTRAINT `fk_operating_system_has_game_operating_system1`
    FOREIGN KEY (`operating_system_id`)
    REFERENCES `steam_db`.`operating_system` (`id_operating_system`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_operating_system_has_game_game1`
    FOREIGN KEY (`game_id`)
    REFERENCES `steam_db`.`game` (`id_game`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `steam_db`.`achievement`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `steam_db`.`achievement` (
  `id_achievement` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NULL,
  `game_id` INT NOT NULL,
  `number_of_people` INT NULL,
  `description` MEDIUMTEXT NULL,
  PRIMARY KEY (`id_achievement`),
  INDEX `fk_achievement_game1_idx` (`game_id` ASC) VISIBLE,
  CONSTRAINT `fk_achievement_game1`
    FOREIGN KEY (`game_id`)
    REFERENCES `steam_db`.`game` (`id_game`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `steam_db`.`game_genre_game`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `steam_db`.`game_genre_game` (
  `game_genre_id_game_genre` INT NOT NULL,
  `game_id_game` INT NOT NULL,
  PRIMARY KEY (`game_genre_id_game_genre`, `game_id_game`),
  INDEX `fk_game_genre_has_game_game1_idx` (`game_id_game` ASC) VISIBLE,
  INDEX `fk_game_genre_has_game_game_genre1_idx` (`game_genre_id_game_genre` ASC) VISIBLE,
  CONSTRAINT `fk_game_genre_has_game_game_genre1`
    FOREIGN KEY (`game_genre_id_game_genre`)
    REFERENCES `steam_db`.`game_genre` (`id_game_genre`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_game_genre_has_game_game1`
    FOREIGN KEY (`game_id_game`)
    REFERENCES `steam_db`.`game` (`id_game`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

INSERT INTO game (id, name, developer_id, release_date, image, description, storage_space) VALUES
(1, 'Zaklínač', 1, '1996-09-22', '1.jpg', 'Epická RPG hra plná dobrodružství a magie', 2048),
(2, 'Cyberpunk 2077', 2, '1997-04-18', '2.jpg', 'Futuristické RPG v otevřeném světě', 4096),
(3, 'Minecraft', 3, '1997-11-18', '3.jpg', 'Sandbox hra pro budování světů', 8192),
(4, 'Fortnite', 4, '1998-06-23', '4.jpg', 'Battle royale s miliony hráčů', 16384),
(5, 'League of Legends', 5, '1999-01-16', '5.jpg', 'MOBA strategická hra pro 5 hráčů', 32768),
(6, 'Dota 2', 6, '1999-08-10', '6.jpg', 'Strategická hra s hrdiny a bohy', 51200),
(7, 'Counter-Strike 2', 7, '2000-03-22', '7.jpg', 'Taktická střílečka z pohledu první osoby', 65536),
(8, 'Baldurova brána 3', 8, '2000-10-25', '8.jpg', 'RPG s rozsáhlými dialogy a volbami', 102400),
(9, 'Elden Ring', 9, '2001-05-21', '9.jpg', 'Soulslike RPG v temném fantasy světě', 2048),
(10, 'Hollow Knight', 10, '2001-12-03', '10.jpg', 'Metroidvania v podzemním království', 4096),
(11, 'Stardew Valley', 11, '2002-07-26', '11.jpg', 'Zemědělský simulátor s RPG prvky', 8192),
(12, 'Celeste', 12, '2003-02-03', '12.jpg', 'Platformer o překonávání překážek', 16384),
(13, 'Hades', 13, '2003-09-26', '13.jpg', 'Roguelike s bohy řecké mytologie', 32768),
(14, 'Disco Elysium', 14, '2004-04-11', '14.jpg', 'Detektivní RPG ve francouzském stylu', 51200),
(15, 'Outrider hvězd', 15, '2004-11-19', '15.jpg', 'Vesmírné RPG s průzkumem planet', 65536),
(16, 'Witcher 3', 16, '2005-06-24', '16.jpg', 'Otevřené RPG v pohádkovém světě', 102400),
(17, 'Red Dead Redemption 2', 17, '2006-01-23', '17.jpg', 'Western RPG s příběhem o vykoupení', 2048),
(18, 'GTA V', 18, '2006-08-25', '18.jpg', 'Akční sandbox v otevřeném světě', 4096),
(19, 'The Last of Us', 19, '2007-03-04', '19.jpg', 'Akční adventura s emočním příběhem', 8192),
(20, 'God of War', 20, '2007-10-13', '20.jpg', 'Akční RPG ve světě norské mytologie', 16384),
(21, 'Spider-Man', 1, '2008-05-13', '21.jpg', 'Akční adventura se Spider-Manem', 32768),
(22, 'Horizon Zero Dawn', 2, '2008-12-15', '22.jpg', 'Post-apokalyptický akční RPG', 51200),
(23, 'Ghost of Tsushima', 3, '2009-07-01', '23.jpg', 'Stealth akční hra v feudálním Japonsku', 65536),
(24, 'Death Stranding', 4, '2010-02-16', '24.jpg', 'Experimentální akční adventura', 102400),
(25, 'Detroit Become Human', 5, '2010-09-14', '25.jpg', 'Detektivní thriller s umělou inteligencí', 2048),
(26, 'Control', 6, '2011-04-27', '26.jpg', 'Akční střílečka s nadpřirozenými silami', 4096),
(27, 'Alan Wake 2', 7, '2011-11-20', '27.jpg', 'Psychologický horor s Alanovou stopou', 8192),
(28, 'Returner', 8, '2012-06-07', '28.jpg', 'Roguelike střílečka ve sci-fi světě', 16384),
(29, 'Deathloop', 9, '2013-01-14', '29.jpg', 'Akční hra se smyčkami času', 32768),
(30, 'Ghostwire Tokyo', 10, '2013-08-04', '30.jpg', 'Duchovní horor v Tokiu', 51200),
(31, 'Kena Bridge of Spirits', 11, '2014-03-11', '31.jpg', 'Akční adventura s duchovou dívkou', 65536),
(32, 'Stray', 12, '2014-10-14', '32.jpg', 'Prozkoumávací adventura se kočkou', 102400),
(33, 'Tunic', 13, '2015-05-27', '33.jpg', 'Puzzle akční adventura s liškou', 2048),
(34, 'Neon White', 14, '2015-12-24', '34.jpg', 'Rybářský simulátor s průchodem', 4096),
(35, 'Sifu', 15, '2016-07-21', '35.jpg', 'Akční bojová hra s kung-fu', 8192),
(36, 'Prodaný ostrov', 16, '2017-02-05', '36.jpg', 'Strategie na tropickém ostrově', 16384),
(37, 'Mortal Kombat 11', 17, '2017-09-08', '37.jpg', 'Bojová hra se smrtelným bojem', 32768),
(38, 'Street Fighter 6', 18, '2018-04-02', '38.jpg', 'Bojová hra nových hrdinů', 51200),
(39, 'Tekken 8', 19, '2018-11-07', '39.jpg', 'Bojová hra se silnými techniky', 65536),
(40, 'Dragon\'s Dogma 2', 20, '2019-06-19', '40.jpg', 'Akční RPG s drakem jako průvodcem', 102400),
(41, 'Final Fantasy XVI', 1, '2020-01-25', '41.jpg', 'JRPG epické fantasy světa Crystalu', 2048),
(42, 'Persona 5 Royal', 2, '2020-08-15', '42.jpg', 'JRPG s osobností a démony', 4096),
(43, 'Sekiro', 3, '2021-03-17', '43.jpg', 'Soulslike ve feudálním Japonsku', 8192),
(44, 'Dark Souls 3', 4, '2021-10-19', '44.jpg', 'Dark fantasy soulslike ve hradu', 16384),
(45, 'Bloodborne', 5, '2022-05-24', '45.jpg', 'Gotické soulslike v zasněžené říši', 32768),
(46, 'Nioh 2', 6, '2022-12-02', '46.jpg', 'Akční RPG v japonském období Edo', 51200),
(47, 'Monster Hunter Rise', 7, '2023-07-20', '47.jpg', 'Lov monster v otevřeném světě', 65536),
(48, 'Monster Hunter World', 8, '2024-02-05', '48.jpg', 'Lov monster v tropickém pralese', 102400),
(49, 'Divinity Original Sin 2', 9, '2024-09-07', '49.jpg', 'Tahovéé RPG s velkou svobodou', 2048),
(50, 'Pathfinder Kingmaker', 10, '1995-04-03', '50.jpg', 'Krpgé ve světě Pathfinderu', 4096),
(51, 'Pillars of Eternity 2', 11, '1995-11-22', '51.jpg', 'RPG s hlubokými volbami ve světě', 8192),
(52, 'Tyranny', 12, '1996-06-17', '52.jpg', 'RPG kde jste tyrán nového království', 16384),
(53, 'Wasteland 3', 13, '1997-01-13', '53.jpg', 'Postapokalyptické RPG s volbami', 32768),
(54, 'XCOM 2', 14, '1997-08-18', '54.jpg', 'Tahová taktika s mimozemšťany', 51200),
(55, 'Phoenix Point', 15, '1998-03-08', '55.jpg', 'Tahová taktika s fenixem', 65536),
(56, 'Into the Breach', 16, '1998-10-08', '56.jpg', 'Tahová roguelike strategie', 102400),
(57, 'Slay the Spire', 17, '1999-05-27', '57.jpg', 'Stavění balíčku s roguelike', 2048),
(58, 'Monster Train', 18, '1999-12-14', '58.jpg', 'Roguelike budování balíčku v pekle', 4096),
(59, 'Inscryption', 19, '2000-07-18', '59.jpg', 'Roguelike s karetní magií v lesích', 8192),
(60, 'Dicey Dungeons', 20, '2001-02-01', '60.jpg', 'Tahová hra s kostičkami', 16384),
(61, 'Loop Hero', 1, '2001-09-09', '61.jpg', 'Smyčkové RPG s budováním mapy', 32768),
(62, 'Roguebook', 2, '2002-04-21', '62.jpg', 'Karetní roguelike ve fantasy světě', 51200),
(63, 'Across the Obelisk', 3, '2002-11-22', '63.jpg', 'Tahová dobrodružná karetní hra', 65536),
(64, 'Nowhere Prophet', 4, '2003-06-21', '64.jpg', 'Karetní hra v postapokalypse', 102400),
(65, 'Griftlands', 5, '2004-01-16', '65.jpg', 'Deckbuilder ve světě pirátů', 2048),
(66, 'Night in the Woods', 6, '2004-08-22', '66.jpg', 'Adventura o mladé lišce v noci', 4096),
(67, 'Oxenfree', 7, '2005-03-21', '67.jpg', 'Adventura o přátelství a tajemstvích', 8192),
(68, 'What Remains of Edith Finch', 8, '2005-10-28', '68.jpg', 'Prozkoumávací hra s rodinnou historií', 16384),
(69, 'Firewatch', 9, '2006-05-24', '69.jpg', 'Survival adventura s fotografem', 32768),
(70, 'Gone Home', 10, '2006-12-11', '70.jpg', 'Prozkoumávání opuštěného domu', 51200),
(71, 'Tacoma', 11, '2007-07-20', '71.jpg', 'Sci-fi prozkoumávání stanice', 65536),
(72, 'Dear Esther', 12, '2008-02-21', '72.jpg', 'Meditativní procházka po pláži', 102400),
(73, 'Everybody\'s Gone to the Rapture', 13, '2008-09-19', '73.jpg', 'Klidná procházka vesnicí', 2048),
(74, 'The Stanley Parable Ultra Deluxe', 14, '2009-04-04', '74.jpg', 'Meta adventura o naraci', 4096),
(75, 'Superliminal', 15, '2009-11-07', '75.jpg', 'Puzzle hra o nekonečném prostoru', 8192),
(76, 'The Witness', 16, '2010-06-16', '76.jpg', 'Puzzle hra se světlem a reflexemi', 16384),
(77, 'Outer Wilds', 17, '2011-01-05', '77.jpg', 'Průzkum vesmíru a záhady slunce', 32768),
(78, 'Return of the Obra Dinn', 18, '2011-08-11', '78.jpg', 'Logická hra na lodi obchodníků', 51200),
(79, 'Her Story', 19, '2012-03-28', '79.jpg', 'Detektivní hra s video záznamy', 65536),
(80, 'Immortality', 20, '2012-10-25', '80.jpg', 'Detektivní hra s filmy', 102400),
(81, 'Pentiment', 1, '2013-05-19', '81.jpg', 'Historická adventura ve středověku', 2048),
(82, 'Norco', 2, '2013-12-27', '82.jpg', 'Cyberpunk noir detektivní hra', 4096),
(83, 'Citizen Sleeper', 3, '2014-07-04', '83.jpg', 'Sci-fi RPG o dělníkovi budoucnosti', 8192),
(84, 'Roadwarden', 4, '2015-02-06', '84.jpg', 'Text RPG ve středověkém světě', 16384),
(85, 'Orcs Must Die 3', 5, '2015-09-28', '85.jpg', 'Věžová obrana s orky', 32768),
(86, 'Deep Rock Galactic', 6, '2016-04-21', '86.jpg', 'Kooperativní těžba ve vesmíru', 51200),
(87, 'Valheim', 7, '2016-11-20', '87.jpg', 'Přežití ve vikingském světě', 65536),
(88, 'Raft', 8, '2017-06-14', '88.jpg', 'Přežití na oceánu na voru', 102400),
(89, 'Subnautica', 9, '2018-01-05', '89.jpg', 'Prozkoumávání podmořského světa', 2048),
(90, 'Green Hell', 10, '2018-08-18', '90.jpg', 'Přežití v deštném pralese', 4096),
(91, 'The Forest', 11, '2019-03-12', '91.jpg', 'Přežití v lese s příšerami', 8192),
(92, 'Sons of the Forest', 12, '2019-10-28', '92.jpg', 'Přežití s mutanty v lese', 16384),
(93, 'Grounded', 13, '2020-05-25', '93.jpg', 'Přežití hmyzu v trávníku', 32768),
(94, 'Conan Exiles', 14, '2020-12-25', '94.jpg', 'Přežití v Cimmerianském světě', 51200),
(95, 'Rust', 15, '2021-07-14', '95.jpg', 'Multiplayerové přežití v divočině', 65536),
(96, 'DayZ', 16, '2022-02-28', '96.jpg', 'Zombie přežití ve velkém světě', 102400),
(97, 'Project Zomboid', 17, '2022-09-27', '97.jpg', 'Zombie přežití v sandbox světě', 2048),
(98, 'RimWorld', 18, '2023-04-11', '98.jpg', 'Kolonizační simulátor s přežitím', 4096),
(99, 'Dwarf Fortress', 19, '2023-11-05', '99.jpg', 'Simulátor trpasličí kolonie', 8192),
(100, 'Caves of Qud', 20, '2024-06-01', '100.jpg', 'Roguelike RPG v mutantním světě', 16384),
(101, 'Nethack', 1, '1995-01-16', '101.jpg', 'Klasický roguelike v podzemí', 32768),
(102, 'Angband', 2, '1995-08-18', '102.jpg', 'Fantasy roguelike s magií', 51200),
(103, 'Tome 4', 3, '1996-03-10', '103.jpg', 'Roguelike tahový RPG', 65536),
(104, 'Cogmind', 4, '1996-10-08', '104.jpg', 'Sci-fi roguelike s robotem', 102400),
(105, 'Brogue', 5, '1997-05-01', '105.jpg', 'Roguelike v temném lese', 2048),
(106, 'Spelunky 2', 6, '1997-12-23', '106.jpg', 'Procedurální jeskyně s hledáním', 4096),
(107, 'Dead Cells', 7, '1998-07-21', '107.jpg', 'Roguelike metroidvania plošinovka', 8192),
(108, 'Rogue Legacy 2', 8, '1999-02-09', '108.jpg', 'Roguelike akční plošinovka', 16384),
(109, 'Curse of the Dead Gods', 9, '1999-09-20', '109.jpg', 'Roguelike s řeckými bohy II', 32768),
(110, 'Catacomb Kids', 10, '2000-04-15', '110.jpg', 'Roguelike plošinovka v katakombách', 51200),
(111, 'Shattered Pixel Dungeon', 11, '2000-11-23', '111.jpg', 'Mobilní roguelike pro Android', 65536),
(112, 'Cardinal Quest 2', 12, '2001-06-10', '112.jpg', 'Roguelike s kouzly a bitvami', 102400),
(113, 'One Step from Eden', 13, '2002-01-28', '113.jpg', 'Akční roguelike s kartami', 2048),
(114, 'Fights in Tight Spaces', 14, '2002-08-05', '114.jpg', 'Bojová hra v úzkých chodbách', 4096),
(115, 'Tactical Breach Wizards', 15, '2003-03-26', '115.jpg', 'Tahová hra čarodějů', 8192),
(116, 'Marvel Snap', 16, '2003-10-14', '116.jpg', 'Digitální karetní hra od Marvelu', 16384),
(117, 'Hearthstone', 17, '2004-05-16', '117.jpg', 'Digitální karetní hra ve fantasy', 32768),
(118, 'Legends of Runeterra', 18, '2004-12-04', '118.jpg', 'Karetní hra v Runeterře', 51200),
(119, 'Gwent', 19, '2005-07-06', '119.jpg', 'Karetní hra z Gwentu zaklínačů', 65536),
(120, 'Eternal Card Game', 20, '2006-02-20', '120.jpg', 'Věčná karetní hra s bohy', 102400),
(121, 'Faeria', 1, '2006-09-25', '121.jpg', 'Karetní strategie s bohem v rukou', 2048),
(122, 'Hand of the Gods', 2, '2007-04-22', '122.jpg', 'Karetní hra se světovou mytologií', 4096),
(123, 'Shadowverse', 3, '2007-11-07', '123.jpg', 'Anime karetní RPG hra', 8192),
(124, 'Mythgard', 4, '2008-06-01', '124.jpg', 'Karetní hra v temném světě', 16384),
(125, 'Artifact 2', 5, '2009-01-08', '125.jpg', 'Karetní hra od Valvu 2.0', 32768),
(126, 'Age of Empires IV', 6, '2009-08-12', '126.jpg', 'Strategie s budováním říše v středověku', 51200),
(127, 'StarCraft 2', 7, '2010-03-20', '127.jpg', 'Vesmírná RTS se Zergy a Protossy', 65536),
(128, 'Warcraft 3 Reforged', 8, '2010-10-23', '128.jpg', 'Klasická RTS ve Warcraftu', 102400),
(129, 'Command & Conquer Remastered', 9, '2011-05-14', '129.jpg', 'RTS z druhé světové války', 2048),
(130, 'Company of Heroes 3', 10, '2011-12-24', '130.jpg', 'RTS v Normandii a dál', 4096),
(131, 'Men of War 2', 11, '2012-07-21', '131.jpg', 'Fantasy RTS ve Warhammeru', 8192),
(132, 'Gates of Hell Ostfront', 12, '2013-02-12', '132.jpg', 'Historická RTS ve feudálním Japonsku', 16384),
(133, 'Warhammer 40k Dawn of War', 13, '2013-09-19', '133.jpg', 'Středověká grand strategie', 32768),
(134, 'Total War Warhammer 3', 14, '2014-04-26', '134.jpg', 'Globální grand strategie v Evropě', 51200),
(135, 'Total War Shogun 2', 15, '2014-11-11', '135.jpg', 'Vojenská grand strategie ve světové válce', 65536),
(136, 'Crusader Kings 3', 16, '2015-06-10', '136.jpg', 'Průmyslová grand strategie 19.st.', 102400),
(137, 'Europa Universalis 4', 17, '2016-01-08', '137.jpg', 'Vesmírná 4X strategie', 2048),
(138, 'Hearts of Iron 4', 18, '2016-08-27', '138.jpg', 'Kolonizace Marsu s přežitím', 4096),
(139, 'Victoria 3', 19, '2017-03-23', '139.jpg', 'Přežití v mrazivém apokalyptickém světě', 8192),
(140, 'Stellaris', 20, '2017-10-01', '140.jpg', 'Strategická obrana proti zombie', 16384),
(141, 'Surviving Mars', 1, '2018-05-07', '141.jpg', 'Automatizační factory hra', 32768),
(142, 'Frostpunk 2', 2, '2018-12-07', '142.jpg', 'Industriální stavitelský simulátor', 51200),
(143, 'They Are Billions', 3, '2019-07-22', '143.jpg', 'Industriální vesmírný simulátor', 65536),
(144, 'Factorio', 4, '2020-02-26', '144.jpg', 'Puzzle factory automatizace', 102400),
(145, 'Satisfactory', 5, '2020-09-28', '145.jpg', 'Strategická obrana s věžemi', 2048),
(146, 'Dyson Sphere Program', 6, '2021-04-27', '146.jpg', 'Epická RPG hra plná dobrodružství a magie', 4096),
(147, 'Shapez 2', 7, '2021-11-25', '147.jpg', 'Futuristické RPG v otevřeném světě', 8192),
(148, 'Mindustry', 8, '2022-06-06', '148.jpg', 'Sandbox hra pro budování světů', 16384),
(149, 'Opus Magnum', 9, '2023-01-21', '149.jpg', 'Battle royale s miliony hráčů', 32768),
(150, 'SpaceChem', 10, '2023-08-11', '150.jpg', 'MOBA strategická hra pro 5 hráčů', 51200),
(151, 'Zachtronics Shenzhen IO', 11, '2024-03-26', '151.jpg', 'Strategická hra s hrdiny a bohy', 65536),
(152, 'TIS-100', 12, '2024-10-15', '152.jpg', 'Taktická střílečka z pohledu první osoby', 102400),
(153, 'Hacknet', 13, '1995-05-24', '153.jpg', 'RPG s rozsáhlými dialogy a volbami', 2048),
(154, 'Quadrilateral Cowboy', 14, '1995-12-06', '154.jpg', 'Soulslike RPG v temném fantasy světě', 4096),
(155, 'Exapunks', 15, '1996-07-20', '155.jpg', 'Metroidvania v podzemním království', 8192),
(156, 'Portal 2', 16, '1997-02-02', '156.jpg', 'Zemědělský simulátor s RPG prvky', 16384),
(157, 'The Talos Principle 2', 17, '1997-09-08', '157.jpg', 'Platformer o překonávání překážek', 32768),
(158, 'Antichamber', 18, '1998-04-26', '158.jpg', 'Roguelike s bohy řecké mytologie', 51200),
(159, 'Quantum Conundrum', 19, '1998-11-07', '159.jpg', 'Detektivní RPG ve francouzském stylu', 65536),
(160, 'Q.U.B.E. 2', 20, '1999-06-03', '160.jpg', 'Vesmírné RPG s průzkumem planet', 102400),
(161, 'Maquette', 1, '2000-01-14', '161.jpg', 'Otevřené RPG v pohádkovém světě', 2048),
(162, 'The Pedestrian', 2, '2000-08-24', '162.jpg', 'Western RPG s příběhem o vykoupení', 4096),
(163, 'A Monster\'s Expedition', 3, '2001-03-02', '163.jpg', 'Akční sandbox v otevřeném světě', 8192),
(164, 'Baba Is You', 4, '2001-10-11', '164.jpg', 'Akční adventura s emočním příběhem', 16384),
(165, 'Stephen\'s Sausage Roll', 5, '2002-05-13', '165.jpg', 'Akční RPG ve světě norské mytologie', 32768),
(166, 'Patrick\'s Parabox', 6, '2002-12-01', '166.jpg', 'Akční adventura se Spider-Manem', 51200),
(167, 'Recursed', 7, '2003-07-20', '167.jpg', 'Post-apokalyptický akční RPG', 65536),
(168, 'Snakebird', 8, '2004-02-02', '168.jpg', 'Stealth akční hra v feudálním Japonsku', 102400),
(169, 'Sokobond', 9, '2004-09-26', '169.jpg', 'Experimentální akční adventura', 2048),
(170, 'English Country Tune', 10, '2005-04-24', '170.jpg', 'Detektivní thriller s umělou inteligencí', 4096),
(171, 'Sokobano', 11, '2005-11-01', '171.jpg', 'Akční střílečka s nadpřirozenými silami', 8192),
(172, 'Picross 3D Round 2', 12, '2006-06-02', '172.jpg', 'Psychologický horor s Alanovou stopou', 16384),
(173, 'Nonograms Katana', 13, '2007-01-20', '173.jpg', 'Roguelike střílečka ve sci-fi světě', 32768),
(174, 'Tametsi', 14, '2007-08-03', '174.jpg', 'Akční hra se smyčkami času', 51200),
(175, 'Hexcells Infinite', 15, '2008-03-22', '175.jpg', 'Duchovní horor v Tokiu', 65536),
(176, 'Minesweeper X', 16, '2008-10-27', '176.jpg', 'Akční adventura s duchovou dívkou', 102400),
(177, '2048 Dimensions', 17, '2009-05-27', '177.jpg', 'Prozkoumávací adventura se kočkou', 2048),
(178, 'Threes', 18, '2009-12-04', '178.jpg', 'Puzzle akční adventura s liškou', 4096),
(179, 'Klocki', 19, '2010-07-12', '179.jpg', 'Rybářský simulátor s průchodem', 8192),
(180, 'Quell Reflect', 20, '2011-02-07', '180.jpg', 'Akční bojová hra s kung-fu', 16384),
(181, 'Prune', 1, '2011-09-16', '181.jpg', 'Strategie na tropickém ostrově', 32768),
(182, 'Alto\'s Odyssey', 2, '2012-04-01', '182.jpg', 'Bojová hra se smrtelným bojem', 51200),
(183, 'Gris', 3, '2012-11-12', '183.jpg', 'Bojová hra nových hrdinů', 65536),
(184, 'Journey', 4, '2013-06-18', '184.jpg', 'Bojová hra se silnými techniky', 102400),
(185, 'Abzu', 5, '2014-01-22', '185.jpg', 'Akční RPG s drakem jako průvodcem', 2048),
(186, 'Flower', 6, '2014-08-19', '186.jpg', 'JRPG epické fantasy světa Crystalu', 4096),
(187, 'Flow', 7, '2015-03-01', '187.jpg', 'JRPG s osobností a démony', 8192),
(188, 'Everything', 8, '2015-10-22', '188.jpg', 'Soulslike ve feudálním Japonsku', 16384),
(189, 'Kind Words', 9, '2016-05-15', '189.jpg', 'Dark fantasy soulslike ve hradu', 32768),
(190, 'Unpacking', 10, '2016-12-28', '190.jpg', 'Gotické soulslike v zasněžené říši', 51200),
(191, 'A Short Hike', 11, '2017-07-12', '191.jpg', 'Akční RPG v japonském období Edo', 65536),
(192, 'Alba A Wildlife Adventure', 12, '2018-02-05', '192.jpg', 'Lov monster v otevřeném světě', 102400),
(193, 'Chicory A Colorful Tale', 13, '2018-09-12', '193.jpg', 'Lov monster v tropickém pralese', 2048),
(194, 'Purrfect Tale', 14, '2019-04-27', '194.jpg', 'Tahovéé RPG s velkou svobodou', 4096),
(195, 'Cats and the Other Lives', 15, '2019-11-22', '195.jpg', 'Krpgé ve světě Pathfinderu', 8192),
(196, 'Little Kitty Big City', 16, '2020-06-20', '196.jpg', 'RPG s hlubokými volbami ve světě', 16384),
(197, 'Neko Atsume 2', 17, '2021-01-19', '197.jpg', 'RPG kde jste tyrán nového království', 32768),
(198, 'Catlateral Damage', 18, '2021-08-16', '198.jpg', 'Postapokalyptické RPG s volbami', 51200),
(199, 'Cat Quest 3', 19, '2022-03-27', '199.jpg', 'Tahová taktika s mimozemšťany', 65536),
(200, 'Warriors All Stars', 20, '2022-10-04', '200.jpg', 'Tahová taktika s fenixem', 102400),
(201, 'Hob', 1, '2023-05-12', '201.jpg', 'Tahová roguelike strategie', 2048),
(202, 'Flinthook', 2, '2023-12-09', '202.jpg', 'Stavění balíčku s roguelike', 4096),
(203, 'Headlander', 3, '2024-07-09', '203.jpg', 'Roguelike budování balíčku v pekle', 8192),
(204, 'Pyre', 4, '1995-02-01', '204.jpg', 'Roguelike s karetní magií v lesích', 16384),
(205, 'Transistor', 5, '1995-09-20', '205.jpg', 'Tahová hra s kostičkami', 32768),
(206, 'Bastion', 6, '1996-04-25', '206.jpg', 'Smyčkové RPG s budováním mapy', 51200),
(207, 'Supergiant Games Collection', 7, '1996-11-11', '207.jpg', 'Karetní roguelike ve fantasy světě', 65536),
(208, 'Hades 2', 8, '1997-06-15', '208.jpg', 'Tahová dobrodružná karetní hra', 102400),
(209, 'Early Access Beta', 9, '1998-01-07', '209.jpg', 'Karetní hra v postapokalypse', 2048),
(210, 'Skul the Hero Slayer', 10, '1998-08-01', '210.jpg', 'Deckbuilder ve světě pirátů', 4096),
(211, 'Dead Cells Return to Castlevania', 11, '1999-03-09', '211.jpg', 'Adventura o mladé lišce v noci', 8192),
(212, 'Blasphemous 2', 12, '1999-10-14', '212.jpg', 'Adventura o přátelství a tajemstvích', 16384),
(213, 'Salt and Sacrifice', 13, '2000-05-16', '213.jpg', 'Prozkoumávací hra s rodinnou historií', 32768),
(214, 'Vigil The Longest Night', 14, '2000-12-01', '214.jpg', 'Survival adventura s fotografem', 51200),
(215, 'Aeterna Noctis', 15, '2001-07-12', '215.jpg', 'Prozkoumávání opuštěného domu', 65536),
(216, 'Pronty', 16, '2002-02-13', '216.jpg', 'Sci-fi prozkoumávání stanice', 102400),
(217, '9 Years of Shadows', 17, '2002-09-05', '217.jpg', 'Meditativní procházka po pláži', 2048),
(218, 'Momodora Moonlit Farewell', 18, '2003-04-26', '218.jpg', 'Klidná procházka vesnicí', 4096),
(219, 'Souldiers', 19, '2003-11-21', '219.jpg', 'Meta adventura o naraci', 8192),
(220, 'Haiku the Robot', 20, '2004-06-25', '220.jpg', 'Puzzle hra o nekonečném prostoru', 16384),
(221, 'Axiom Verge 2', 1, '2005-01-08', '221.jpg', 'Puzzle hra se světlem a reflexemi', 32768),
(222, 'Metroid Dread', 2, '2005-08-21', '222.jpg', 'Průzkum vesmíru a záhady slunce', 51200),
(223, 'Hollow Knight Silksong Preview', 3, '2006-03-22', '223.jpg', 'Logická hra na lodi obchodníků', 65536),
(224, 'Environmental Station Alpha', 4, '2006-10-09', '224.jpg', 'Detektivní hra s video záznamy', 102400),
(225, 'Timespinner', 5, '2007-05-25', '225.jpg', 'Detektivní hra s filmy', 2048),
(226, 'Bloodstained Ritual', 6, '2007-12-04', '226.jpg', 'Historická adventura ve středověku', 4096),
(227, 'Castlevania Symphony', 7, '2008-07-08', '227.jpg', 'Cyberpunk noir detektivní hra', 8192),
(228, 'Cave Story Plus', 8, '2009-02-20', '228.jpg', 'Sci-fi RPG o dělníkovi budoucnosti', 16384),
(229, 'La Mulana 2', 9, '2009-09-03', '229.jpg', 'Text RPG ve středověkém světě', 32768),
(230, 'Owlboy', 10, '2010-04-20', '230.jpg', 'Věžová obrana s orky', 51200),
(231, 'Zaklínač', 11, '2010-11-13', '231.jpg', 'Kooperativní těžba ve vesmíru', 65536),
(232, 'Cyberpunk 2077', 12, '2011-06-20', '232.jpg', 'Přežití ve vikingském světě', 102400),
(233, 'Minecraft', 13, '2012-01-26', '233.jpg', 'Přežití na oceánu na voru', 2048),
(234, 'Fortnite', 14, '2012-08-15', '234.jpg', 'Prozkoumávání podmořského světa', 4096),
(235, 'League of Legends', 15, '2013-03-03', '235.jpg', 'Přežití v deštném pralese', 8192),
(236, 'Dota 2', 16, '2013-10-12', '236.jpg', 'Přežití v lese s příšerami', 16384),
(237, 'Counter-Strike 2', 17, '2014-05-25', '237.jpg', 'Přežití s mutanty v lese', 32768),
(238, 'Baldurova brána 3', 18, '2014-12-27', '238.jpg', 'Přežití hmyzu v trávníku', 51200),
(239, 'Elden Ring', 19, '2015-07-12', '239.jpg', 'Přežití v Cimmerianském světě', 65536),
(240, 'Hollow Knight', 20, '2016-02-28', '240.jpg', 'Multiplayerové přežití v divočině', 102400),
(241, 'Stardew Valley', 1, '2016-09-19', '241.jpg', 'Zombie přežití ve velkém světě', 2048),
(242, 'Celeste', 2, '2017-04-21', '242.jpg', 'Zombie přežití v sandbox světě', 4096),
(243, 'Hades', 3, '2017-11-24', '243.jpg', 'Kolonizační simulátor s přežitím', 8192),
(244, 'Disco Elysium', 4, '2018-06-11', '244.jpg', 'Simulátor trpasličí kolonie', 16384),
(245, 'Outrider hvězd', 5, '2019-01-05', '245.jpg', 'Roguelike RPG v mutantním světě', 32768),
(246, 'Witcher 3', 6, '2019-08-20', '246.jpg', 'Klasický roguelike v podzemí', 51200),
(247, 'Red Dead Redemption 2', 7, '2020-03-11', '247.jpg', 'Fantasy roguelike s magií', 65536),
(248, 'GTA V', 8, '2020-10-26', '248.jpg', 'Roguelike tahový RPG', 102400),
(249, 'The Last of Us', 9, '2021-05-20', '249.jpg', 'Sci-fi roguelike s robotem', 2048),
(250, 'God of War', 10, '2021-12-26', '250.jpg', 'Roguelike v temném lese', 4096),
(251, 'Baldurs Gate 3: Patch 7', 3, '2024-04-18', '251.jpg', 'Expanded RPG with new epilogues and evil endings', 8192),
(252, 'Fallout 4 Next-Gen Update', 7, '2024-04-25', '252.jpg', 'Post-apocalyptic RPG with rebuilt lighting and textures', 32768),
(253, 'Satisfactory 1.0', 11, '2024-09-10', '253.jpg', 'First-person factory automation on an alien planet', 8192),
(254, 'Prince of Persia Lost Crown', 2, '2024-01-18', '254.jpg', 'Metroidvania set in a cursed Persian mountain', 4096),
(255, 'Helldivers 2', 14, '2024-02-08', '255.jpg', 'Co-op shooter defending democracy across the galaxy', 32768),
(256, 'Unicorn Overlord', 9, '2024-03-08', '256.jpg', 'Tactical RPG to reclaim a fantasy kingdom', 4096),
(257, 'Manor Lords', 17, '2024-04-26', '257.jpg', 'Medieval city-builder with real-time battles', 8192),
(258, 'Animal Well', 5, '2024-05-09', '258.jpg', 'Metroidvania hidden inside a mysterious living painting', 2048),
(259, 'Hades II Early Access', 6, '2024-05-06', '259.jpg', 'Roguelike sequel with new gods and the witch Melinoe', 4096),
(260, 'Black Myth Wukong', 18, '2024-08-20', '260.jpg', 'Action RPG inspired by the Chinese legend Monkey King', 102400),
(261, 'Astro Bot', 15, '2024-09-06', '261.jpg', '3D platformer celebrating PlayStation history and heroes', 16384);

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;